name: PR-checkout

on: 
  pull_request:
    branches:
      - dev 
      - stage
      - prod

jobs:
  guard:
    name: PR-Guard

    runs-on: ubuntu-latest

    steps: 
    - name: fail if PR is not allowed
      shell: bash
      run: |
        if [[ "${{ github.base_ref }}" == "stage" && "${{ github.head_ref }}" != "dev" ]]; then
          echo "Error due to pull request not from dev"
          exit 1
        elif [[ "${{ github.base_ref }}" == "prod" && "${{ github.head_ref }}" != "stage" ]]; then
          echo "Error due to pull request not from Stage"
          exit 1
        else [[ "${{ github.base_ref }}" == "dev" && "${{ github.head_ref }}" != "main" ]]
          echo "Error due to pull request not from main"
          exit 1
        fi
          echo "Pull Request successful, from right branch"
